import course1 from "../../public/Assets/Landing Page/course_banner3.svg"
import course2 from "../../public/Assets/Landing Page/course_banner4.svg";
import course3 from "../../public/Assets/Landing Page/course_banner1.svg";


export const courses = [
   {
    id: 1,
    thumbnail: course1,
    title: "Digital Marketing for Beginners",
    instructor: "YashBusinessman",
    rating: "4.8",
    reviews: "4560",
    language: "Hindi • English",
    price: "499",
    badge: "Bestseller",
    category: "Marketing",
    type: "skool",
    duration: "6h 30min",
  },
  {
    id: 2,
    thumbnail: course2,
    title: "UI & UX Design with Adobe XD & Figma",
    instructor: "YashBusinessman",
    rating: "4.7",
    reviews: "3210",
    language: "English",
    price: "399",
    category: "Design",
    type: "ebook",
    duration: "8h 20min",
  },
  {
    id: 3,
    thumbnail: course2,
    title: "Advanced UI & UX Design",
    instructor: "YashBusinessman",
    rating: "4.6",
    reviews: "2100",
    language: "English",
    price: "399",
    category: "Design",
    type: "course",
     duration: "5h 20min",
  },
  {
    id: 4,
    thumbnail: course1,
    title: "Instagram Marketing Mastery",
    instructor: "YashBusinessman",
    rating: "4.9",
    reviews: "5200",
    language: "Hindi",
    price: "599",
    badge: "Trending",
    category: "Marketing",
    type: "ebook",
     duration: "1h 20min",
  },
  {
    id: 5,
    thumbnail: course3,
    title: "Instagram Mastery",
    instructor: "YashBusinessman",
    rating: "4.9",
    reviews: "5200",
    language: "Hindi",
    price: "599",
    badge: "Trending",
    category: "App Development",
    type: "free",
     duration: "3h 20min",
  },
];
